### PR TITLE
Adding RISC-V Vector support for CHERIoT

### PR DESCRIPTION
**Pull request by vmurali**
Companion to https://github.com/CHERIoT-Platform/sail-riscv/pull/2

### CODE REVIEW

**Comment by vmurali** [comment]
@rmn30 @nwf-msr companion to https://github.com/CHERIoT-Platform/sail-riscv/pull/2

**Comment by marnovandermaas** [comment]
If I'm not mistaken this adds the vanilla vector extension to CHERIoT Sail. How do we deal with vectorized memory addresses? Is it worth describing the interaction between CHERIoT and the V extension in the ISA document before changing the Sail?

**Comment by vmurali** [comment]
If you look at, for instance, [this](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#183-v-vector-extension-for-application-processors), it uses the function [`ext_data_get_addr`](https://github.com/CHERIoT-Platform/sail-riscv/blob/cf541bea6be2d612c9bc91af032ab277a3756512/model/riscv_insts_vext_mem.sail#L91C15-L91C21) that is effectively [overwritten](https://github.com/microsoft/cheriot-sail/blob/main/src/cheri_addr_checks.sail#L167) in cheriot-sail. So everything works immediately.

**Comment by rmn30** [comment]
Yes, the memory checks should just work if they follow the conventions of the existing RISC-V memory access instructions. We do need to think about the CSRs though. They probably need to be added to the allow list.

**Comment by vmurali** [comment]
Good point. I overlooked that. Let me see if that can be fixed.

**Comment by vmurali** [comment]
Where is the allow list? https://github.com/CHERIoT-Platform/sail-riscv/blob/cf541bea6be2d612c9bc91af032ab277a3756512/model/riscv_csr_map.sail#L171-L177 seems to be uncommented.

**Comment by rmn30** [comment]
This one for code running without access system regs perm: https://github.com/microsoft/cheriot-sail/blob/09ef3a7daad39293596e06dcf9079194b47f3e8c/src/cheri_addr_checks.sail#L229

**Comment by vmurali** [comment]
> This one for code running without access system regs perm:
> 
> https://github.com/microsoft/cheriot-sail/blob/09ef3a7daad39293596e06dcf9079194b47f3e8c/src/cheri_addr_checks.sail#L229

Fixed. Thanks!

**Pull request closed without merging**
